#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "Entrez un nom de package a tester!"
    exit 1
fi

package_info=$(dpkg -S $(which -a $1) 2> /dev/null)

if [ -z "$package_info" ]; then
    echo "INSTALLÉ"
else
    echo "NON INSTALLÉ"
fi